/* The following code was generated by JFlex 1.4.3 on 7/18/14 10:34 AM */

package de.halirutan.mathematica.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import java.util.LinkedList;
import de.halirutan.mathematica.parsing.MathematicaElementTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 7/18/14 10:34 AM from the specification file
 * <tt>Mathematica.flex</tt>
 */
class _MathematicaLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int PUT_START = 6;
  public static final int GET_START = 10;
  public static final int IN_STRING = 4;
  public static final int YYINITIAL = 0;
  public static final int PUT_RHS = 8;
  public static final int GET_RHS = 12;
  public static final int IN_COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\22\0\1\3\1\43\1\30"+
    "\1\26\1\7\1\27\1\51\1\52\1\4\1\6\1\5\1\44\1\46"+
    "\1\25\1\23\1\37\1\10\1\22\1\16\1\17\1\20\1\20\1\20"+
    "\1\21\1\21\1\21\1\40\1\42\1\33\1\41\1\35\1\50\1\36"+
    "\32\15\1\13\1\12\1\14\1\24\1\47\1\11\32\15\1\31\1\34"+
    "\1\32\1\45\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\4\0\1\2\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\2\1\13\1\14\4\11"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\4\1\2\45\1\46\1\47\1\2\1\47\1\50\1\51"+
    "\2\52\1\53\1\54\1\55\1\56\1\10\1\0\2\11"+
    "\1\57\2\4\2\0\1\60\1\0\1\61\1\62\1\63"+
    "\1\64\1\20\1\65\1\66\1\67\1\70\1\71\1\72"+
    "\1\73\1\74\1\75\1\76\1\77\1\100\1\101\1\102"+
    "\1\103\1\104\1\105\1\106\1\107\1\110\1\111\1\112"+
    "\1\113\1\0\1\114\1\115\1\116\1\117\1\120\1\121"+
    "\1\122\1\123\1\124\2\45\1\0\1\11\4\0\1\125"+
    "\1\126\1\127\1\130\1\131\1\132\1\133\1\134\1\135"+
    "\1\136\1\11\1\0\1\11\1\10\2\11";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\u0158\0\u0183\0\u01ae\0\u0102\0\u01d9\0\u0204\0\u022f\0\u025a"+
    "\0\u0102\0\u0102\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c"+
    "\0\u0387\0\u03b2\0\u03dd\0\u0102\0\u0102\0\u0102\0\u0408\0\u0433"+
    "\0\u045e\0\u0489\0\u04b4\0\u04df\0\u050a\0\u0535\0\u0560\0\u058b"+
    "\0\u05b6\0\u0102\0\u05e1\0\u0102\0\u060c\0\u0102\0\u0637\0\u0183"+
    "\0\u0662\0\u0102\0\u068d\0\u06b8\0\u0102\0\u0102\0\u06e3\0\u06e3"+
    "\0\u070e\0\u0739\0\u0102\0\u06e3\0\u0764\0\u0102\0\u0102\0\u0102"+
    "\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u0102\0\u0102\0\u083b\0\u0866"+
    "\0\u0891\0\u08bc\0\u08e7\0\u0102\0\u0102\0\u0102\0\u0102\0\u0912"+
    "\0\u093d\0\u0102\0\u0102\0\u0102\0\u0102\0\u0102\0\u0102\0\u0968"+
    "\0\u0102\0\u0102\0\u0993\0\u0102\0\u0102\0\u0102\0\u09be\0\u0102"+
    "\0\u0102\0\u0102\0\u0102\0\u0102\0\u0102\0\u09e9\0\u0a14\0\u0a3f"+
    "\0\u0102\0\u0102\0\u0102\0\u0102\0\u0102\0\u0102\0\u0a6a\0\u0102"+
    "\0\u0102\0\u0102\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c"+
    "\0\u0b97\0\u0102\0\u0102\0\u0102\0\u0102\0\u0102\0\u0102\0\u0102"+
    "\0\u0102\0\u0102\0\u0102\0\u0bc2\0\u0bc2\0\u0bed\0\u0102\0\u0c18"+
    "\0\u0c43";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\2\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\15\1\23\1\24\2\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\4\57\1\60\1\61\1\62\44\57\12\63\1\64"+
    "\15\63\1\65\22\63\1\66\1\67\1\70\1\71\47\66"+
    "\1\72\2\67\2\7\1\72\1\7\4\72\2\7\7\72"+
    "\1\7\1\72\11\7\2\72\2\7\1\72\1\7\1\72"+
    "\1\7\3\72\1\7\1\73\1\67\1\74\1\75\47\73"+
    "\54\0\2\10\53\0\1\11\54\0\1\76\52\0\1\77"+
    "\33\0\1\100\20\0\2\15\1\101\3\0\6\15\35\0"+
    "\1\102\2\0\1\16\1\103\4\0\5\16\1\104\36\0"+
    "\1\15\1\0\1\105\3\0\1\15\36\0\1\106\1\107"+
    "\10\0\1\110\44\0\1\102\2\0\1\25\1\103\4\0"+
    "\5\25\1\104\1\111\33\0\1\102\2\0\1\25\1\103"+
    "\4\0\3\25\1\16\1\25\1\104\1\111\33\0\1\102"+
    "\2\0\1\16\1\103\4\0\5\16\1\104\1\111\33\0"+
    "\1\102\2\0\1\25\1\103\4\0\5\25\1\104\37\0"+
    "\1\104\5\0\5\104\1\112\67\0\1\113\1\114\36\0"+
    "\1\115\7\0\1\116\3\0\1\117\21\0\1\120\4\0"+
    "\6\120\3\0\1\121\53\0\1\33\56\0\1\122\1\123"+
    "\1\124\3\0\1\125\45\0\1\126\1\127\52\0\1\130"+
    "\3\0\1\131\16\0\1\132\30\0\1\133\21\0\1\134"+
    "\15\0\1\135\12\0\1\136\1\137\1\140\1\141\1\142"+
    "\45\0\1\143\2\0\1\144\1\145\34\0\1\146\15\0"+
    "\1\147\1\0\1\150\51\0\1\151\51\0\1\152\52\0"+
    "\1\153\2\0\1\154\53\0\1\155\30\0\1\156\23\0"+
    "\1\157\54\0\1\160\1\0\4\57\3\0\44\57\6\0"+
    "\1\161\44\0\12\63\1\0\15\63\1\0\22\63\1\0"+
    "\1\162\1\163\7\0\1\162\15\0\1\162\23\0\2\67"+
    "\53\0\1\71\47\0\1\72\4\0\1\72\1\0\4\72"+
    "\2\0\7\72\1\0\1\72\11\0\2\72\2\0\1\72"+
    "\1\0\1\72\1\0\3\72\4\0\1\75\56\0\1\15"+
    "\5\0\1\15\61\0\1\164\33\0\1\102\2\0\1\165"+
    "\1\166\4\0\5\165\1\167\34\0\1\102\2\0\1\104"+
    "\1\103\4\0\5\104\31\0\1\106\60\0\1\170\5\0"+
    "\1\170\61\0\1\171\51\0\1\172\70\0\1\173\21\0"+
    "\1\120\4\0\6\120\40\0\1\121\5\0\5\121\65\0"+
    "\1\174\53\0\1\175\37\0\1\176\12\0\1\177\24\0"+
    "\1\200\5\0\5\200\71\0\1\201\52\0\1\202\60\0"+
    "\1\203\4\0\1\162\61\0\1\204\5\0\5\204\2\0"+
    "\1\205\32\0\1\102\2\0\1\165\5\0\5\165\1\206"+
    "\37\0\1\165\5\0\5\165\1\167\37\0\1\206\5\0"+
    "\5\206\37\0\2\170\3\0\1\207\6\170\40\0\1\210"+
    "\4\0\6\210\40\0\1\204\5\0\5\204\35\0\1\102"+
    "\2\0\1\206\5\0\5\206\40\0\1\210\1\103\3\0"+
    "\6\210\1\211\37\0\1\211\1\103\3\0\6\211\30\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3182];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\4\0\1\11\4\1\1\11\4\1\2\11"+
    "\11\1\3\11\13\1\1\11\1\1\1\11\1\1\1\11"+
    "\3\1\1\11\2\1\2\11\4\1\1\11\2\1\3\11"+
    "\1\1\1\0\2\1\2\11\1\1\2\0\1\1\1\0"+
    "\4\11\2\1\6\11\1\1\2\11\1\1\3\11\1\1"+
    "\6\11\2\1\1\0\6\11\1\1\3\11\1\1\1\0"+
    "\1\1\4\0\12\11\1\1\1\0\1\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    // This adds support for nested states. I'm no JFlex pro, so maybe this is overkill, but it works quite well.
    private final LinkedList<Integer> states = new LinkedList();

    private void yypushstate(int state) {
        states.addFirst(yystate());
        yybegin(state);
    }
    private void yypopstate() {
        final int state = states.removeFirst();
        yybegin(state);
    }



  _MathematicaLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _MathematicaLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 106) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { return MathematicaElementTypes.TIMES;
          }
        case 95: break;
        case 4: 
          { return MathematicaElementTypes.WHITE_SPACE;
          }
        case 96: break;
        case 43: 
          { yybegin(GET_RHS); return MathematicaElementTypes.WHITE_SPACE;
          }
        case 97: break;
        case 39: 
          { yypushback(1); yybegin(PUT_RHS);
          }
        case 98: break;
        case 25: 
          { return MathematicaElementTypes.DIVIDE;
          }
        case 99: break;
        case 11: 
          { return MathematicaElementTypes.LEFT_BRACKET;
          }
        case 100: break;
        case 62: 
          { return MathematicaElementTypes.COMPOSITION;
          }
        case 101: break;
        case 77: 
          { return MathematicaElementTypes.UNEQUAL;
          }
        case 102: break;
        case 40: 
          { yybegin(PUT_RHS); return MathematicaElementTypes.WHITE_SPACE;
          }
        case 103: break;
        case 82: 
          { return MathematicaElementTypes.BLANK_SEQUENCE;
          }
        case 104: break;
        case 68: 
          { return MathematicaElementTypes.TAG_SET;
          }
        case 105: break;
        case 58: 
          { return MathematicaElementTypes.OR;
          }
        case 106: break;
        case 31: 
          { return MathematicaElementTypes.INFIX_CALL;
          }
        case 107: break;
        case 74: 
          { return MathematicaElementTypes.UNSET;
          }
        case 108: break;
        case 71: 
          { return MathematicaElementTypes.RULE_DELAYED;
          }
        case 109: break;
        case 49: 
          { return MathematicaElementTypes.UP_SET;
          }
        case 110: break;
        case 54: 
          { yybegin(GET_START); return MathematicaElementTypes.GET;
          }
        case 111: break;
        case 41: 
          { yybegin(YYINITIAL); return MathematicaElementTypes.STRINGIFIED_IDENTIFIER;
          }
        case 112: break;
        case 80: 
          { return MathematicaElementTypes.STRING_EXPRESSION;
          }
        case 113: break;
        case 17: 
          { return MathematicaElementTypes.OUT;
          }
        case 114: break;
        case 5: 
          { return MathematicaElementTypes.LEFT_PAR;
          }
        case 115: break;
        case 84: 
          { yypopstate(); return MathematicaElementTypes.COMMENT;
          }
        case 116: break;
        case 53: 
          { return MathematicaElementTypes.SLOT_SEQUENCE;
          }
        case 117: break;
        case 18: 
          { yypushstate(IN_STRING); return MathematicaElementTypes.STRING_LITERAL_BEGIN;
          }
        case 118: break;
        case 57: 
          { return MathematicaElementTypes.LESS_EQUAL;
          }
        case 119: break;
        case 33: 
          { return MathematicaElementTypes.BLANK;
          }
        case 120: break;
        case 22: 
          { return MathematicaElementTypes.ALTERNATIVE;
          }
        case 121: break;
        case 65: 
          { return MathematicaElementTypes.REPLACE_ALL;
          }
        case 122: break;
        case 44: 
          { yypushstate(IN_COMMENT); return MathematicaElementTypes.COMMENT;
          }
        case 123: break;
        case 51: 
          { return MathematicaElementTypes.RULE;
          }
        case 124: break;
        case 85: 
          { return MathematicaElementTypes.REPEATED_NULL;
          }
        case 125: break;
        case 81: 
          { return MathematicaElementTypes.DEFAULT;
          }
        case 126: break;
        case 28: 
          { return MathematicaElementTypes.SEMICOLON;
          }
        case 127: break;
        case 1: 
          { return MathematicaElementTypes.COMMENT;
          }
        case 128: break;
        case 16: 
          { return MathematicaElementTypes.SLOT;
          }
        case 129: break;
        case 29: 
          { return MathematicaElementTypes.EXCLAMATION_MARK;
          }
        case 130: break;
        case 15: 
          { return MathematicaElementTypes.MINUS;
          }
        case 131: break;
        case 42: 
          { yypushback(1); yybegin(GET_RHS);
          }
        case 132: break;
        case 9: 
          { return MathematicaElementTypes.NUMBER;
          }
        case 133: break;
        case 61: 
          { return MathematicaElementTypes.GREATER_EQUAL;
          }
        case 134: break;
        case 88: 
          { return MathematicaElementTypes.APPLY1;
          }
        case 135: break;
        case 12: 
          { return MathematicaElementTypes.RIGHT_BRACKET;
          }
        case 136: break;
        case 66: 
          { return MathematicaElementTypes.MAP;
          }
        case 137: break;
        case 59: 
          { return MathematicaElementTypes.RIGHT_ASSOCIATION;
          }
        case 138: break;
        case 34: 
          { return MathematicaElementTypes.QUESTION_MARK;
          }
        case 139: break;
        case 20: 
          { return MathematicaElementTypes.RIGHT_BRACE;
          }
        case 140: break;
        case 73: 
          { return MathematicaElementTypes.SET_DELAYED;
          }
        case 141: break;
        case 72: 
          { return MathematicaElementTypes.DOUBLE_COLON;
          }
        case 142: break;
        case 19: 
          { return MathematicaElementTypes.LEFT_BRACE;
          }
        case 143: break;
        case 86: 
          { return MathematicaElementTypes.UP_SET_DELAYED;
          }
        case 144: break;
        case 36: 
          { return MathematicaElementTypes.DERIVATIVE;
          }
        case 145: break;
        case 3: 
          { return MathematicaElementTypes.LINE_BREAK;
          }
        case 146: break;
        case 63: 
          { return MathematicaElementTypes.APPLY;
          }
        case 147: break;
        case 21: 
          { return MathematicaElementTypes.LESS;
          }
        case 148: break;
        case 7: 
          { return MathematicaElementTypes.RIGHT_PAR;
          }
        case 149: break;
        case 79: 
          { return MathematicaElementTypes.INCREMENT;
          }
        case 150: break;
        case 69: 
          { return MathematicaElementTypes.DIVIDE_BY;
          }
        case 151: break;
        case 75: 
          { return MathematicaElementTypes.EQUAL;
          }
        case 152: break;
        case 60: 
          { yybegin(PUT_START); return MathematicaElementTypes.PUT;
          }
        case 153: break;
        case 24: 
          { return MathematicaElementTypes.PREFIX_CALL;
          }
        case 154: break;
        case 78: 
          { return MathematicaElementTypes.ADD_TO;
          }
        case 155: break;
        case 2: 
          { return MathematicaElementTypes.BAD_CHARACTER;
          }
        case 156: break;
        case 55: 
          { return MathematicaElementTypes.LEFT_ASSOCIATION;
          }
        case 157: break;
        case 14: 
          { return MathematicaElementTypes.POWER;
          }
        case 158: break;
        case 26: 
          { return MathematicaElementTypes.COLON;
          }
        case 159: break;
        case 91: 
          { yypushback(2); return MathematicaElementTypes.SET;
          }
        case 160: break;
        case 67: 
          { return MathematicaElementTypes.POSTFIX;
          }
        case 161: break;
        case 10: 
          { return MathematicaElementTypes.BACK_TICK;
          }
        case 162: break;
        case 56: 
          { return MathematicaElementTypes.STRING_JOIN;
          }
        case 163: break;
        case 87: 
          { yybegin(PUT_START); return MathematicaElementTypes.PUT_APPEND;
          }
        case 164: break;
        case 13: 
          { return MathematicaElementTypes.POINT;
          }
        case 165: break;
        case 89: 
          { return MathematicaElementTypes.REPLACE_REPEATED;
          }
        case 166: break;
        case 94: 
          { return MathematicaElementTypes.BLANK_NULL_SEQUENCE;
          }
        case 167: break;
        case 83: 
          { return MathematicaElementTypes.AND;
          }
        case 168: break;
        case 45: 
          { return MathematicaElementTypes.NON_COMMUTATIVE_MULTIPLY;
          }
        case 169: break;
        case 50: 
          { return MathematicaElementTypes.DECREMENT;
          }
        case 170: break;
        case 38: 
          { yypopstate(); return MathematicaElementTypes.STRING_LITERAL_END;
          }
        case 171: break;
        case 64: 
          { return MathematicaElementTypes.RIGHT_COMPOSITION;
          }
        case 172: break;
        case 47: 
          { return MathematicaElementTypes.ACCURACY;
          }
        case 173: break;
        case 23: 
          { return MathematicaElementTypes.GREATER;
          }
        case 174: break;
        case 46: 
          { return MathematicaElementTypes.TIMES_BY;
          }
        case 175: break;
        case 93: 
          { return MathematicaElementTypes.UNSAME_Q;
          }
        case 176: break;
        case 37: 
          { return MathematicaElementTypes.STRING_LITERAL;
          }
        case 177: break;
        case 48: 
          { return MathematicaElementTypes.REPEATED;
          }
        case 178: break;
        case 70: 
          { return MathematicaElementTypes.CONDITION;
          }
        case 179: break;
        case 32: 
          { return MathematicaElementTypes.COMMA;
          }
        case 180: break;
        case 27: 
          { return MathematicaElementTypes.SET;
          }
        case 181: break;
        case 52: 
          { return MathematicaElementTypes.SUBTRACT_FROM;
          }
        case 182: break;
        case 76: 
          { return MathematicaElementTypes.SPAN;
          }
        case 183: break;
        case 8: 
          { return MathematicaElementTypes.IDENTIFIER;
          }
        case 184: break;
        case 90: 
          { return MathematicaElementTypes.MAP_ALL;
          }
        case 185: break;
        case 92: 
          { return MathematicaElementTypes.SAME_Q;
          }
        case 186: break;
        case 30: 
          { return MathematicaElementTypes.PLUS;
          }
        case 187: break;
        case 35: 
          { return MathematicaElementTypes.FUNCTION;
          }
        case 188: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
